agoge-pricing/force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <description>The city of a country state</description>
    <label>City</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agoge-pricing/force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

agoge-pricing/force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agoge-pricing/force-app/main/default/objects/Freight__c/Freight__c.object-meta.xml
<CustomObject>
    <label>Freight</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Freights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agoge-pricing/force-app/main/default/objects/Freight__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Freights</relationshipLabel>
    <relationshipName>Freights</relationshipName>
    <type>Lookup</type>
</CustomField>

agoge-pricing/force-app/main/default/objects/Freight__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Freights</relationshipLabel>
    <relationshipName>Freights</relationshipName>
    <type>Lookup</type>
</CustomField>

agoge-pricing/force-app/main/default/objects/Freight__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Freights</relationshipLabel>
    <relationshipName>Freights</relationshipName>
    <type>Lookup</type>
</CustomField>

agoge-pricing/force-app/main/default/objects/Freight__c/fields/ProductHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Hierarchy</label>
    <referenceTo>ProductHierarchy__c</referenceTo>
    <relationshipLabel>Freights</relationshipLabel>
    <relationshipName>Freights</relationshipName>
    <type>Lookup</type>
</CustomField>

agoge-pricing/force-app/main/default/objects/Freight__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Freights</relationshipLabel>
    <relationshipName>Freights</relationshipName>
    <type>Lookup</type>
</CustomField>

agoge-pricing/force-app/main/default/objects/ProductHierarchy__c/ProductHierarchy__c.object-meta.xml
<CustomObject>
    <label>Product Hierarchy</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Hierarchy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agoge-pricing/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>The state of the country</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agoge-pricing/force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookip to the country</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>States</relationshipLabel>
    <relationshipName>States</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

agoge-pricing/force-app/main/default/classes/FreightHelper.cls
public with sharing class FreightHelper {
    public static void checkFreightFields(List<Freight__c> freightsList){
        Set<Id> productIds = new Set<Id>();
        Set<Id> productHierarchyIds = new Set<Id>();
        Set<Id> cityIds = new Set<Id>();
        Set<Id> stateIds = new Set<Id>();
        Set<Id> countryIds = new Set<Id>();

        for (Freight__c freight : freightsList) {
            if (freight.Product__c != null && freight.ProductHierarchy__c != null) {
                freight.addError('Não é permitido preencher ambos os campos de Produto.');
            } else if (freight.Product__c != null) {
                productIds.add(freight.Product__c);
            } else if (freight.ProductHierarchy__c != null) {
                productHierarchyIds.add(freight.ProductHierarchy__c);
            } else {
                freight.addError('É obrigatório preencher pelo menos um campo de Produto.');
            }

            if (freight.City__c != null) {
                if (freight.State__c != null || freight.Country__c != null) {
                    freight.addError('Não é permitido preencher o campo City em conjunto com State ou Country.');
                } else {
                    cityIds.add(freight.City__c);
                }
            } else if (freight.State__c != null) {
                if (freight.City__c != null || freight.Country__c != null) {
                    freight.addError('Não é permitido preencher o campo State em conjunto com City ou Country.');
                } else {
                    stateIds.add(freight.State__c);
                }
            } else if (freight.Country__c != null) {
                if (freight.City__c != null || freight.State__c != null) {
                    freight.addError('Não é permitido preencher o campo Country em conjunto com City ou State.');
                } else {
                    countryIds.add(freight.Country__c);
                }
            } else {
                freight.addError('É obrigatório preencher pelo menos um campo de Localidade.');
            }
        }
    }

    public static void checkDuplicateFreights(List<Freight__c> freightsList){
        Set<Id> productIds = new Set<Id>();
        Set<Id> productHierarchyIds = new Set<Id>();
        Set<Id> cityIds = new Set<Id>();
        Set<Id> stateIds = new Set<Id>();
        Set<Id> countryIds = new Set<Id>();

        for (Freight__c freight : freightsList) {
            if (freight.Product__c != null) {
                productIds.add(freight.Product__c);
            }
            if (freight.ProductHierarchy__c != null) {
                productHierarchyIds.add(freight.ProductHierarchy__c);
            }
            if (freight.City__c != null) {
                cityIds.add(freight.City__c);
            }
            if (freight.State__c != null) {
                stateIds.add(freight.State__c);
            }
            if (freight.Country__c != null) {
                countryIds.add(freight.Country__c);
            }
        }

        List<Freight__c> registeredFreights = [
            SELECT Id, Name, Product__c, ProductHierarchy__c, City__c, State__c, Country__c, Value__c 
            FROM Freight__c 
            WHERE Status__c = 'Approved' 
            AND (Product__c IN : productIds OR ProductHierarchy__c IN : productHierarchyIds)     
            AND (City__c IN : cityIds OR State__c IN : stateIds OR Country__c IN : countryIds)
        ];

        Set<String> freightSet = new Set<String>();
        for(Freight__c freight : registeredfreights){
            String freightKey = freight.Product__c + '-' + freight.ProductHierarchy__c + '-' + freight.City__c + '-' + freight.State__c + '-' + freight.Country__c;
            freightSet.add(freightKey);
        }

        for (Freight__c freight : freightsList) {
            String freightKey = freight.Product__c + '-' + freight.ProductHierarchy__c + '-' + freight.City__c + '-' + freight.State__c + '-' + freight.Country__c;
            if(freightSet.contains(freightKey)){
                freight.addError('Não é permitido o cadastro de Margens duplicadas!');
            }
        }
    }
}