agoge-pricing/force-app/main/default/objects/AccountGroup__c/AccountGroup__c.object-meta.xml
<CustomObject>
    <description>A group of accounts</description>
    <label>Account Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agoge-pricing/force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <description>The city of a country state</description>
    <label>City</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agoge-pricing/force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

agoge-pricing/force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agoge-pricing/force-app/main/default/objects/Margin__c/Margin__c.object-meta.xml
<CustomObject>
    <label>Margin</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Margins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agoge-pricing/force-app/main/default/objects/Margin__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Margins</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

agoge-pricing/force-app/main/default/objects/Margin__c/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Group</label>
    <referenceTo>AccountGroup__c</referenceTo>
    <relationshipLabel>Margins</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

agoge-pricing/force-app/main/default/objects/Margin__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Margins</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

agoge-pricing/force-app/main/default/objects/Margin__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Margins</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

agoge-pricing/force-app/main/default/objects/Margin__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Margins</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

agoge-pricing/force-app/main/default/objects/Margin__c/fields/ProductHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Hierarchy</label>
    <referenceTo>ProductHierarchy__c</referenceTo>
    <relationshipLabel>Margins</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

agoge-pricing/force-app/main/default/objects/Margin__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Margins</relationshipLabel>
    <relationshipName>Margins</relationshipName>
    <type>Lookup</type>
</CustomField>

agoge-pricing/force-app/main/default/objects/Margin__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

agoge-pricing/force-app/main/default/objects/ProductHierarchy__c/ProductHierarchy__c.object-meta.xml
<CustomObject>
    <label>Product Hierarchy</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Hierarchy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agoge-pricing/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>The state of the country</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agoge-pricing/force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookip to the country</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>States</relationshipLabel>
    <relationshipName>States</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Agoge de Pricing/classes/MarginHelper.cls
public with sharing class MarginHelper {
    
    public static void checkMarginFields(List<Margin__c> marginsList){
        Set<Id> productIds = new Set<Id>();
        Set<Id> productHierarchyIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();
        Set<Id> accountGroupIds = new Set<Id>();
        Set<Id> cityIds = new Set<Id>();
        Set<Id> stateIds = new Set<Id>();
        Set<Id> countryIds = new Set<Id>();

        for (Margin__c margin : marginsList) {
          // Verifica a categoria Produto
            if (margin.Product__c != null && margin.ProductHierarchy__c != null) {
                margin.addError('Não é permitido preencher ambos os campos de Produto.');
            } else if (margin.Product__c != null) {
                productIds.add(margin.Product__c);
            } else if (margin.ProductHierarchy__c != null) {
                productHierarchyIds.add(margin.ProductHierarchy__c);
            } else {
                margin.addError('É obrigatório preencher pelo menos um campo de Produto.');
            }

            // Verifica a categoria Cliente
            if (margin.Account__c != null && margin.AccountGroup__c != null) {
                margin.addError('Não é permitido preencher ambos os campos de Cliente.');
            } else if (margin.Account__c != null) {
                accountIds.add(margin.Account__c);
            } else if (margin.AccountGroup__c != null) {
                accountGroupIds.add(margin.AccountGroup__c);
            } else {
                margin.addError('É obrigatório preencher pelo menos um campo de Cliente.');
            }

            // Verifica a categoria Localidade
            if (margin.City__c != null) {
                if (margin.State__c != null || margin.Country__c != null) {
                    margin.addError('Não é permitido preencher o campo City em conjunto com State ou Country.');
                } else {
                    cityIds.add(margin.City__c);
                }
            } else if (margin.State__c != null) {
                if (margin.City__c != null || margin.Country__c != null) {
                    margin.addError('Não é permitido preencher o campo State em conjunto com City ou Country.');
                } else {
                    stateIds.add(margin.State__c);
                }
            } else if (margin.Country__c != null) {
                if (margin.City__c != null || margin.State__c != null) {
                    margin.addError('Não é permitido preencher o campo Country em conjunto com City ou State.');
                } else {
                    countryIds.add(margin.Country__c);
                }
            } else {
                margin.addError('É obrigatório preencher pelo menos um campo de Localidade.');
            }
        }
    }

    public static void checkDuplicateMargins(List<Margin__c> marginsList){
        Set<Id> productIds = new Set<Id>();
        Set<Id> productHierarchyIds = new Set<Id>();
        Set<Id> accountIds = new Set<Id>();
        Set<Id> accountGroupIds = new Set<Id>();
        Set<Id> cityIds = new Set<Id>();
        Set<Id> stateIds = new Set<Id>();
        Set<Id> countryIds = new Set<Id>();

        for (Margin__c margin : marginsList) {
            if (margin.Product__c != null) {
                productIds.add(margin.Product__c);
            }
            if (margin.ProductHierarchy__c != null) {
                productHierarchyIds.add(margin.ProductHierarchy__c);
            }
            if (margin.Account__c != null) {
                accountIds.add(margin.Account__c);
            }
            if (margin.AccountGroup__c != null) {
                accountGroupIds.add(margin.AccountGroup__c);
            }
            if (margin.City__c != null) {
                cityIds.add(margin.City__c);
            }
            if (margin.State__c != null) {
                stateIds.add(margin.State__c);
            }
            if (margin.Country__c != null) {
                countryIds.add(margin.Country__c);
            }
        }

        List<Margin__c> registeredMargins = [
            SELECT Id, Name, Product__c, ProductHierarchy__c, Account__c, AccountGroup__c, City__c, State__c, Country__c, Value__c 
            FROM Margin__c 
            WHERE Status__c = 'Approved' 
            AND (
                Product__c IN : productIds 
                OR ProductHierarchy__c IN : productHierarchyIds
                )    
            AND (
                Account__c IN : accountIds 
                OR AccountGroup__c IN : accountGroupIds
                )    
            AND (
                City__c IN : cityIds    
                OR State__c IN : stateIds    
                OR Country__c IN : countryIds
            )
        ];

        Set<String> marginSet = new Set<String>();

        for(Margin__c margin : registeredMargins){
            String marginKey = margin.Product__c + '-' + margin.ProductHierarchy__c + '-' + margin.Account__c + '-' + margin.AccountGroup__c + '-' + margin.City__c + '-' + margin.State__c + '-' + margin.Country__c;
            marginSet.add(marginKey);
        }

        for(Margin__c margin : marginsList){
            String marginKey = margin.Product__c + '-' + margin.ProductHierarchy__c + '-' + margin.Account__c + '-' + margin.AccountGroup__c + '-' + margin.City__c + '-' + margin.State__c + '-' + margin.Country__c;
            if(marginSet.contains(marginKey)){
                margin.addError('Não é permitido o cadastro de Margens duplicadas!');
            }
        }
    }
}