agoge-pricing/force-app/main/default/objects/DistributionCenter__c/DistributionCenter__c.object-meta.xml
<CustomObject>
    <description>The distribution center</description>
    <label>Distribution Center</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agoge-pricing/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>The state of the country</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agoge-pricing/force-app/main/default/objects/Tax__c/Tax__c.object-meta.xml
<CustomObject>
    <label>Tax</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

agoge-pricing/force-app/main/default/objects/Tax__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distribution Center</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Taxes</relationshipLabel>
    <relationshipName>Taxes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

agoge-pricing/force-app/main/default/objects/Tax__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Taxes</relationshipLabel>
    <relationshipName>Taxes</relationshipName>
    <type>Lookup</type>
</CustomField>

agoge-pricing/force-app/main/default/objects/Tax__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Taxes</relationshipLabel>
    <relationshipName>Taxes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

agoge-pricing/force-app/main/default/objects/Tax__c/fields/TaxCost__c.field-meta.xml
<CustomField>
    <fullName>TaxCost__c</fullName>
    <label>Tax Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

agoge-pricing/force-app/main/default/classes/TaxHelper.cls
public with sharing class TaxHelper {
    public static void checkDuplicateTaxes(List<Tax__c> taxList){
        Set<Id> productIds = new Set<Id>();
        Set<Id> distributionCenterIds = new Set<Id>();
        Set<Id> stateIds = new Set<Id>();

        for(Tax__c tax : taxList){
            if(tax.Product__c != null){
                productIds.add(tax.Product__c);
            }
            
            if(tax.DistributionCenter__c != null){
                distributionCenterIds.add(tax.DistributionCenter__c);
            }
           
            if(tax.State__c != null){
                stateIds.add(tax.State__c);
            }
        }
        
        List<Tax__c> registeredTaxes = [
            SELECT Name, Product__c, DistributionCenter__c, State__c, TaxCost__c 
            FROM Tax__c
            WHERE Status__c = 'Approved'
            AND(
                Product__c IN: productIds
                AND DistributionCenter__c IN: distributionCenterIds
                AND State__c IN: stateIds
            )
        ];

        Set<String> taxSet = new Set<String>();

        for(Tax__c tax : registeredTaxes){
            String taxKey = tax.Product__c + ':' + tax.DistributionCenter__c + ':' + tax.State__c + ':' + String.valueOf(tax.TaxCost__c);
            taxSet.add(taxKey);
        }

        for(Tax__c tax : taxList){
            String taxKey = tax.Product__c + ':' + tax.DistributionCenter__c + ':' + tax.State__c + ':' + String.valueOf(tax.TaxCost__c);
            if(taxSet.contains(taxKey)){
                tax.addError('Não é permitido o cadastro de Impostos duplicados!');
            }
        }
    }
}